version: "3.3"

services:
  nodejs:
    container_name: htf-2020_game-web-tech_nodejs
    image: htf-2020_game-web-tech_nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # App Port
      - 80:3001
      # Socket Port
      - 3005:3005
      # Inspect port
      - 5850:5850
    volumes:
      - ./src:/dist/src:delegated

      # Block local modules
      - /dist/node_modules